In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
results = pd.read_csv('/home/yaroslav/PycharmProjects/Algorithms/Numerical_methods/Partial different equations/results1.csv')

In [3]:
results

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>t</th>
      <th>$$ ||u|| (t) $$</th>
      <th>e(t)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.0</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.0</td>
      <td>0.270000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.0</td>
      <td>0.480000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.0</td>
      <td>0.630000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.0</td>
      <td>0.720000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.0</td>
      <td>0.750000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.0</td>
      <td>0.750000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0.0</td>
      <td>0.750000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.0</td>
      <td>0.750000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0.0</td>
      <td>0.750000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0.0</td>
      <td>0.750000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0.1</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>12</th>
      <td>0.1</td>
      <td>0.496676</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.1</td>
      <td>0.636313</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>14</th>
      <td>0.1</td>
      <td>0.718911</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>15</th>
      <td>0.1</td>
      <td>0.744469</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>16</th>
      <td>0.1</td>
      <td>0.744469</td>
      <td>0.000303</td>
    </tr>
    <tr>
      <th>17</th>
      <td>0.1</td>
      <td>0.744469</td>
      <td>0.060291</td>
    </tr>
    <tr>
      <th>18</th>
      <td>0.1</td>
      <td>0.744469</td>
      <td>0.120255</td>
    </tr>
    <tr>
      <th>19</th>
      <td>0.1</td>
      <td>0.744469</td>
      <td>0.180194</td>
    </tr>
    <tr>
      <th>20</th>
      <td>0.1</td>
      <td>0.744469</td>
      <td>0.240109</td>
    </tr>
    <tr>
      <th>21</th>
      <td>0.1</td>
      <td>0.744469</td>
      <td>0.240109</td>
    </tr>
    <tr>
      <th>22</th>
      <td>0.2</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>23</th>
      <td>0.2</td>
      <td>0.665095</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0.2</td>
      <td>0.733706</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25</th>
      <td>0.2</td>
      <td>0.743938</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>26</th>
      <td>0.2</td>
      <td>0.743938</td>
      <td>0.120179</td>
    </tr>
    <tr>
      <th>27</th>
      <td>0.2</td>
      <td>0.743938</td>
      <td>0.120179</td>
    </tr>
    <tr>
      <th>28</th>
      <td>0.2</td>
      <td>0.743938</td>
      <td>0.120179</td>
    </tr>
    <tr>
      <th>29</th>
      <td>0.2</td>
      <td>0.743938</td>
      <td>0.234424</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1081</th>
      <td>9.8</td>
      <td>0.038291</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1082</th>
      <td>9.8</td>
      <td>0.043581</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1083</th>
      <td>9.8</td>
      <td>0.043581</td>
      <td>0.642806</td>
    </tr>
    <tr>
      <th>1084</th>
      <td>9.8</td>
      <td>0.043581</td>
      <td>0.642806</td>
    </tr>
    <tr>
      <th>1085</th>
      <td>9.8</td>
      <td>0.043581</td>
      <td>0.642806</td>
    </tr>
    <tr>
      <th>1086</th>
      <td>9.8</td>
      <td>0.043581</td>
      <td>0.642806</td>
    </tr>
    <tr>
      <th>1087</th>
      <td>9.8</td>
      <td>0.043581</td>
      <td>0.642806</td>
    </tr>
    <tr>
      <th>1088</th>
      <td>9.8</td>
      <td>0.043581</td>
      <td>0.642806</td>
    </tr>
    <tr>
      <th>1089</th>
      <td>9.9</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1090</th>
      <td>9.9</td>
      <td>0.011028</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1091</th>
      <td>9.9</td>
      <td>0.023767</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1092</th>
      <td>9.9</td>
      <td>0.043505</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1093</th>
      <td>9.9</td>
      <td>0.045136</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1094</th>
      <td>9.9</td>
      <td>0.045136</td>
      <td>0.745016</td>
    </tr>
    <tr>
      <th>1095</th>
      <td>9.9</td>
      <td>0.045136</td>
      <td>0.745016</td>
    </tr>
    <tr>
      <th>1096</th>
      <td>9.9</td>
      <td>0.045136</td>
      <td>0.745016</td>
    </tr>
    <tr>
      <th>1097</th>
      <td>9.9</td>
      <td>0.045136</td>
      <td>0.745016</td>
    </tr>
    <tr>
      <th>1098</th>
      <td>9.9</td>
      <td>0.045136</td>
      <td>0.745016</td>
    </tr>
    <tr>
      <th>1099</th>
      <td>9.9</td>
      <td>0.045136</td>
      <td>0.745016</td>
    </tr>
    <tr>
      <th>1100</th>
      <td>10.0</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1101</th>
      <td>10.0</td>
      <td>0.011893</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1102</th>
      <td>10.0</td>
      <td>0.025643</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1103</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1104</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.762273</td>
    </tr>
    <tr>
      <th>1105</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.774300</td>
    </tr>
    <tr>
      <th>1106</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.774300</td>
    </tr>
    <tr>
      <th>1107</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.774300</td>
    </tr>
    <tr>
      <th>1108</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.774300</td>
    </tr>
    <tr>
      <th>1109</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.774300</td>
    </tr>
    <tr>
      <th>1110</th>
      <td>10.0</td>
      <td>0.044460</td>
      <td>0.774300</td>
    </tr>
  </tbody>
</table>
<p>1111 rows × 3 columns</p>
</div>

In [4]:
results2 = pd.read_csv('/home/yaroslav/PycharmProjects/Algorithms/Numerical_methods/Partial different equations/results2.csv')

In [5]:
results2

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>x</th>
      <th>u(x)</th>
      <th>e(x)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.0</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.1</td>
      <td>0.011893</td>
      <td>0.258107</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.2</td>
      <td>-0.025643</td>
      <td>0.505643</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.3</td>
      <td>-0.044460</td>
      <td>0.674460</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.4</td>
      <td>-0.042273</td>
      <td>0.762273</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.5</td>
      <td>-0.024300</td>
      <td>0.774300</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.6</td>
      <td>0.001575</td>
      <td>0.718425</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0.7</td>
      <td>0.026146</td>
      <td>0.603854</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.8</td>
      <td>0.039837</td>
      <td>0.440163</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0.9</td>
      <td>0.033641</td>
      <td>0.236359</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1.0</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
  </tbody>
</table>
</div>